{{- $studio := .Values }}
{{- if or $studio.auth.token.value $studio.config.natsWsAuthToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trogon-atlas-studio.fullname" . }}-auth
  labels:
    {{- include "trogon-atlas-studio.labels" . | nindent 4 }}
    app.kubernetes.io/component: studio
type: Opaque
stringData:
  {{- if $studio.auth.token.value }}
  {{ $studio.auth.token.key }}: {{ $studio.auth.token.value | quote }}
  {{- end }}
  {{- if $studio.config.natsWsAuthToken.value }}
  nats-ws-token: {{ $studio.config.natsWsAuthToken.value | quote }}
  {{- end }}
{{- end }}
