//! Property-based tests for `validate_branch_name` (Phase 1: Isolation).
//!
//! Studio's own JS branch-name validator is covered by the studio<->server
//! bridge tests; this file covers only the Rust validator in
//! `trogon_atlas_server::conv::validate_branch_name`.
//!
//! Grammar under test: a non-empty name, not the reserved value `"meta"`
//! (case-insensitive), with at most one `/`-separated segment pair, each
//! segment a valid id component (`trogon_atlas_core::validate_id_component`:
//! ASCII alphanumeric plus `-`/`_`/`.`, not `.`/`..`, no leading dot, <=200
//! chars).

#![allow(clippy::unwrap_used, clippy::expect_used)]

use proptest::prelude::*;
use trogon_atlas_server::conv::validate_branch_name;

fn valid_segment() -> impl Strategy<Value = String> {
    "[a-zA-Z0-9][a-zA-Z0-9_.-]{0,20}".prop_filter("must not be reserved-looking on its own", |s| {
        s != "." && s != ".."
    })
}

fn valid_branch_name() -> impl Strategy<Value = String> {
    prop_oneof![
        valid_segment(),
        (valid_segment(), valid_segment()).prop_map(|(a, b)| format!("{a}/{b}")),
    ]
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]

    /// Every name generated by the grammar itself must be accepted.
    #[test]
    fn valid_grammar_names_are_accepted(name in valid_branch_name()) {
        prop_assert!(
            validate_branch_name(&name).is_ok(),
            "valid-by-construction branch name rejected: {name:?}"
        );
    }

    /// Inserting an illegal character into an otherwise-valid single
    /// segment must always be rejected.
    #[test]
    fn illegal_char_is_rejected(seg in valid_segment(), bad in prop::sample::select(vec![' ', '/', '\\', ':', '@', '!', '?', '\n', '\t'])) {
        // '/' is handled by its own two-slash test below (it changes
        // segment structure rather than injecting a charset violation
        // inside a segment), so only assert here for the other chars --
        // but '/' inserted mid-segment still produces more than one '/'
        // when the original had none, which the multi-slash branch
        // covers too. Skip '/' here to avoid double-purpose assertions.
        prop_assume!(bad != '/');
        let mutated = format!("{seg}{bad}{seg}");
        prop_assert!(
            validate_branch_name(&mutated).is_err(),
            "name with illegal char accepted: {mutated:?}"
        );
    }

    /// An empty segment (leading slash, trailing slash, or doubled slash)
    /// must always be rejected: `validate_id_component` rejects the empty
    /// string.
    #[test]
    fn empty_segment_is_rejected(seg in valid_segment()) {
        for mutated in [format!("/{seg}"), format!("{seg}/"), format!("{seg}//{seg}")] {
            prop_assert!(
                validate_branch_name(&mutated).is_err(),
                "name with an empty segment accepted: {mutated:?}"
            );
        }
    }

    /// More than one `/` (i.e. more than two segments) must always be
    /// rejected, regardless of what the segments themselves look like.
    #[test]
    fn two_slashes_is_rejected(a in valid_segment(), b in valid_segment(), c in valid_segment()) {
        let mutated = format!("{a}/{b}/{c}");
        prop_assert!(
            validate_branch_name(&mutated).is_err(),
            "name with two '/' accepted: {mutated:?}"
        );
    }

    /// A segment over the 200-char id-component ceiling must always be
    /// rejected, whether it is the whole name or one half of a two-segment
    /// name.
    #[test]
    fn oversize_segment_is_rejected(c in "[a-zA-Z0-9]", other in valid_segment()) {
        let long = c.repeat(201);
        prop_assert!(
            validate_branch_name(&long).is_err(),
            "201-char single-segment name accepted"
        );
        let mutated = format!("{other}/{long}");
        prop_assert!(
            validate_branch_name(&mutated).is_err(),
            "name with an oversize second segment accepted: {mutated:?}"
        );
    }

    /// The reserved name "meta" is rejected regardless of case, since it
    /// collides with the `"meta."` metadata-row scan prefix
    /// (`trogon_atlas_store::key::is_reserved_branch_name`).
    #[test]
    fn reserved_name_is_rejected_case_insensitively(
        case_variant in prop::sample::select(vec!["meta", "META", "Meta", "mEtA"]),
    ) {
        prop_assert!(
            validate_branch_name(case_variant).is_err(),
            "reserved branch name accepted: {case_variant:?}"
        );
    }
}

#[test]
fn empty_name_is_rejected() {
    assert!(validate_branch_name("").is_err());
}
