{{- $key := .Values.spicedb.presharedKey }}
{{- if and $key.value (not $key.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trogon-atlas-server.fullname" . }}-spicedb
  labels:
    {{- include "trogon-atlas-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
type: Opaque
stringData:
  {{ $key.key }}: {{ $key.value | quote }}
{{- end }}
